import { getLatestVersion } from "../../scripts/registry.ts";

const { version, url, sha512 } = await getLatestVersion("npm", "6.x");

console.log("Latest version of NPM 6.x:", version);

Deno.writeTextFile(
  new URL("./default.nix", import.meta.url),
  `# This file was autogenerated. Edit the update.ts file instead.
{pkgs ? import <nixpkgs> { inherit system; }, system ? builtins.currentSystem}:

pkgs.stdenv.mkDerivation rec {
  name = "npm";
  version = "${version}";
  src = pkgs.fetchurl {
    url = "${url}";
    sha512 = "${sha512}";
  };
  doCheck = true;
  phases = [ "unpackPhase" "installPhase" ];
  installPhase = ''
    mkdir $out
    cp -r * $out
    chmod +x $out/bin/{npm,npx,node-gyp-bin/node-gyp}
  '';
  meta.priority = "100"; # Prevents collision with Node's built-in npm
}
`
);
