# This file has been generated by node2nix 1.11.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {};
in
{
  "npm-8.x" = nodeEnv.buildNodePackage {
    name = "npm";
    packageName = "npm";
    version = "8.13.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/npm/-/npm-8.13.2.tgz";
      sha512 = "aS6q/QKxkw9mTX8gR7Ft38BcRkW1i+h3sI1yAFmfQ30Yl1a1G4ZX3oNGDzaLCilU5ThFZQBS1F4ZSZsrVxJ7HA==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "a package manager for JavaScript";
      homepage = "https://docs.npmjs.com/";
      license = "Artistic-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "npm-7.x" = nodeEnv.buildNodePackage {
    name = "npm";
    packageName = "npm";
    version = "7.24.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/npm/-/npm-7.24.2.tgz";
      sha512 = "120p116CE8VMMZ+hk8IAb1inCPk4Dj3VZw29/n2g6UI77urJKVYb7FZUDW8hY+EBnfsjI/2yrobBgFyzo7YpVQ==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "a package manager for JavaScript";
      homepage = "https://docs.npmjs.com/";
      license = "Artistic-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "npm-6.x" = nodeEnv.buildNodePackage {
    name = "npm";
    packageName = "npm";
    version = "6.14.17";
    src = fetchurl {
      url = "https://registry.npmjs.org/npm/-/npm-6.14.17.tgz";
      sha512 = "CxEDn1ydVRPDl4tHrlnq+WevYAhv4GF2AEHzJKQ4prZDZ96IS3Uo6t0Sy6O9kB6XzqkI+J00WfYCqqk0p6IJ1Q==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "a package manager for JavaScript";
      homepage = "https://docs.npmjs.com/";
      license = "Artistic-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "yarn-1.x" = nodeEnv.buildNodePackage {
    name = "yarn";
    packageName = "yarn";
    version = "1.22.19";
    src = fetchurl {
      url = "https://registry.npmjs.org/yarn/-/yarn-1.22.19.tgz";
      sha512 = "/0V5q0WbslqnwP91tirOvldvYISzaqhClxzyUKXYxs07yUILIs5jx/k6CFe8bvKSkds5w+eiOqta39Wk3WxdcQ==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "📦🐈 Fast, reliable, and secure dependency management.";
      license = "BSD-2-Clause";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "pnpm-7.x" = nodeEnv.buildNodePackage {
    name = "pnpm";
    packageName = "pnpm";
    version = "7.5.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/pnpm/-/pnpm-7.5.0.tgz";
      sha512 = "sb9wJNyx/d8l3Gze2jI1y8BGNbb/ga+JT3SrGNiH+C5KbtZ4wmgePBWGjaiGugcpT9+vQ5MO//+QlVWhMCpedQ==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Fast, disk space efficient package manager";
      homepage = "https://pnpm.io";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "pnpm-6.x" = nodeEnv.buildNodePackage {
    name = "pnpm";
    packageName = "pnpm";
    version = "6.33.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/pnpm/-/pnpm-6.33.0.tgz";
      sha512 = "BytlfB6lpU6kqoqVORIxVbPsRQ+9nLrugJUXorpOhB6XsCyXOYR9w+2Rf6cGGoLVUaMfzzSbHnMgxfgTg8KxyA==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Fast, disk space efficient package manager";
      homepage = "https://pnpm.io";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
